#include <hwpedit/editor.hpp>
#include <hwpedit/unicode.hpp>
#include <algorithm>
namespace he {
Editor::Editor(){selection.anchor=selection.caret={document.sections.first().body.blocks.first()->id,0};}
void Editor::load(Document d){document=std::move(d);undo_.clear();redo_.clear();historyBytes_=0;state_=savedState_=0;nextState_=1;auto p=document.paragraphs(false);selection={};if(!p.isEmpty())selection.anchor=selection.caret={p.first().block->id,0};if(changed)changed();}
bool Editor::setSelection(Position a,Position b){for(auto p:{a,b}){auto n=document.block(p.paragraph);if(!n||!n->paragraph()||p.offset<0||p.offset>n->paragraph()->length()||!isGraphemeBoundary(n->paragraph()->text(),p.offset))return false;}selection={a,b};if(changed)changed();return true;}
bool Editor::apply(const Command&c,bool forward){auto copy=document;for(const auto&p:c.flows)if(!copy.replaceFlow(p.id,forward?p.after:p.before))return false;for(const auto&p:c.blocks)if(!copy.replaceBlock(p.id,forward?p.after:p.before))return false;for(const auto&p:c.pages){bool found=false;for(auto&s:copy.sections)if(s.id==p.section){s.page=forward?p.after:p.before;found=true;++copy.revision;}if(!found)return false;}auto valid=copy.validate();if(!valid){lastError=valid.error().message;return false;}document=std::move(copy);selection=forward?c.after:c.before;state_=forward?c.stateAfter:c.stateBefore;if(changed)changed();return true;}
bool Editor::execute(Command c){lastError.clear();c.before=selection;c.stateBefore=state_;c.stateAfter=nextState_++;if(!apply(c,true))return false;redo_.clear();c.cost=1024;for(const auto&p:c.blocks){if(p.before->paragraph())c.cost+=p.before->paragraph()->length()*4;if(p.after->paragraph())c.cost+=p.after->paragraph()->length()*4;}for(const auto&p:c.flows)c.cost+=(p.before.blocks.size()+p.after.blocks.size())*32;historyBytes_+=c.cost;undo_.push_back(std::move(c));while(historyBytes_>historyBudget&&undo_.size()>1){historyBytes_-=undo_.front().cost;undo_.pop_front();}return true;}
bool Editor::undo(){if(undo_.empty())return false;auto c=undo_.back();if(!apply(c,false))return false;historyBytes_-=c.cost;undo_.pop_back();redo_.push_back(std::move(c));return true;}
bool Editor::redo(){if(redo_.empty())return false;auto c=redo_.back();if(!apply(c,true))return false;redo_.pop_back();historyBytes_+=c.cost;undo_.push_back(std::move(c));return true;}
static bool editable(const BlockPtr&b){return b&&b->paragraph()&&!b->source.opaque;}
QString Editor::selectedText()const{if(selection.empty())return {};auto a=selection.anchor,b=selection.caret;auto list=document.paragraphs();int ai=-1,bi=-1;for(int i=0;i<list.size();++i){if(list[i].block->id==a.paragraph)ai=i;if(list[i].block->id==b.paragraph)bi=i;}if(ai<0||bi<0)return {};if(ai>bi||(ai==bi&&a.offset>b.offset)){std::swap(ai,bi);std::swap(a,b);}QStringList out;for(int i=ai;i<=bi;++i){QString s=list[i].block->paragraph()->text();out.append(s.mid(i==ai?a.offset:0,(i==bi?b.offset:int(s.size()))-(i==ai?a.offset:0)));}return out.join('\n');}
bool Editor::insertRuns(QVector<Run> runs){auto a=selection.anchor,z=selection.caret;auto first=document.block(a.paragraph),last=document.block(z.paragraph);if(!editable(first)||!editable(last)){lastError="This paragraph contains opaque data and is protected from unsafe edits";return false;}Command c;c.name="텍스트 입력";int inserted=0;for(const auto&r:runs)inserted+=r.length();if(a.paragraph==z.paragraph){if(a.offset>z.offset)std::swap(a,z);auto p=replaceText(*first->paragraph(),a.offset,z.offset,std::move(runs));if(!p){lastError=p.error().message;return false;}auto n=std::make_shared<Block>(*first);n->value=*p;n->source.dirty=true;c.blocks.append({first->id,first,n});c.after.anchor=c.after.caret={first->id,a.offset+inserted};}
else {Id f=document.paragraphFlow(a.paragraph);if(!f||f!=document.paragraphFlow(z.paragraph)){lastError="Cross-cell structural editing is not permitted";return false;}auto flow=document.flow(f);if(!flow)return false;int ai=-1,zi=-1;for(int i=0;i<flow->blocks.size();++i){if(flow->blocks[i]->id==a.paragraph)ai=i;if(flow->blocks[i]->id==z.paragraph)zi=i;}if(ai<0||zi<0)return false;if(ai>zi){std::swap(ai,zi);std::swap(a,z);std::swap(first,last);}for(int i=ai;i<=zi;++i)if(!editable(flow->blocks[i])){lastError="Selection contains a protected block";return false;}auto n=std::make_shared<Block>(*first);auto p=*first->paragraph();p.runs=sliceRuns(p,0,a.offset);p.runs+=runs;p.runs+=sliceRuns(*last->paragraph(),z.offset,last->paragraph()->length());p.runs=normalizeRuns(p.runs);if(p.runs.isEmpty())p.runs.append(Run{});n->value=p;n->source.dirty=true;auto after=*flow;after.blocks.remove(ai,zi-ai+1);after.blocks.insert(ai,n);c.flows.append({f,*flow,after});c.after.anchor=c.after.caret={first->id,a.offset+inserted};}return execute(std::move(c));}
bool Editor::insert(const QString&input){QString s=normalizeNewlines(input);if(!validUnicode(s)){lastError="Invalid Unicode input";return false;}auto b=document.block(selection.caret.paragraph);if(!editable(b))return false;const auto style=b->paragraph()->styleAt(selection.caret.offset);if(!s.contains('\n'))return insertRuns({Run{s,style,{},{},{},{}}});
    // A multiline paste is one atomic flow replacement, never a loop of visible edits.
    auto a=selection.anchor,z=selection.caret;Id f=document.paragraphFlow(a.paragraph);if(!f||f!=document.paragraphFlow(z.paragraph))return false;auto flow=document.flow(f);if(!flow)return false;int ai=-1,zi=-1;for(int i=0;i<flow->blocks.size();++i){if(flow->blocks[i]->id==a.paragraph)ai=i;if(flow->blocks[i]->id==z.paragraph)zi=i;}if(ai<0||zi<0)return false;if(ai>zi||(ai==zi&&a.offset>z.offset)){std::swap(ai,zi);std::swap(a,z);}for(int i=ai;i<=zi;++i)if(!editable(flow->blocks[i]))return false;auto start=flow->blocks[ai],end=flow->blocks[zi];auto lines=s.split('\n',Qt::KeepEmptyParts);QVector<BlockPtr> added;for(int i=0;i<lines.size();++i){auto n=std::make_shared<Block>(*start);if(i)n->id=newId();auto p=*start->paragraph();p.runs.clear();if(i==0)p.runs=sliceRuns(*start->paragraph(),0,a.offset);p.runs.append(Run{lines[i],style,{},{},{},{}});if(i==lines.size()-1)p.runs+=sliceRuns(*end->paragraph(),z.offset,end->paragraph()->length());p.runs=normalizeRuns(p.runs);if(p.runs.isEmpty())p.runs.append(Run{{},style,{},{},{},{}});n->value=p;n->source.dirty=true;added.append(n);}auto after=*flow;after.blocks.remove(ai,zi-ai+1);for(int i=0;i<added.size();++i)after.blocks.insert(ai+i,added[i]);Command c;c.name="여러 문단 붙여넣기";c.flows.append({f,*flow,after});c.after.anchor=c.after.caret={added.last()->id,int(lines.last().size())};return execute(std::move(c));}
bool Editor::erase(bool back){if(!selection.empty())return insertRuns({});auto b=document.block(selection.caret.paragraph);if(!editable(b))return false;auto s=b->paragraph()->text();int p=selection.caret.offset;if((back&&p>0)||(!back&&p<s.size())){auto old=selection;selection.anchor.offset=back?previousGrapheme(s,p):nextGrapheme(s,p);bool ok=insertRuns({});if(!ok)selection=old;else undo_.back().before=old;return ok;}auto f=document.flow(document.paragraphFlow(b->id));if(!f)return false;int i=-1;for(int j=0;j<f->blocks.size();++j)if(f->blocks[j]->id==b->id)i=j;int other=i+(back?-1:1);if(other<0||other>=f->blocks.size()||!editable(f->blocks[other]))return false;auto old=selection;selection.anchor={f->blocks[other]->id,back?f->blocks[other]->paragraph()->length():0};bool ok=insertRuns({});if(!ok)selection=old;else undo_.back().before=old;return ok;}
bool Editor::splitParagraph(bool pageBreak){if(!selection.empty()){lastError="Collapse or replace the selection before splitting";return false;}auto b=document.block(selection.caret.paragraph);if(!editable(b))return false;auto flow=document.flow(document.paragraphFlow(b->id));if(!flow)return false;int at=-1;for(int i=0;i<flow->blocks.size();++i)if(flow->blocks[i]->id==b->id)at=i;if(at<0)return false;auto l=std::make_shared<Block>(*b),r=std::make_shared<Block>(*b);r->id=newId();auto p=*b->paragraph(),q=p;p.runs=sliceRuns(p,0,selection.caret.offset);q.runs=sliceRuns(q,selection.caret.offset,q.length());if(p.runs.isEmpty())p.runs.append(Run{{},b->paragraph()->styleAt(0),{},{},{},{}});if(q.runs.isEmpty())q.runs.append(Run{{},b->paragraph()->styleAt(selection.caret.offset),{},{},{},{}});q.style.breakBefore=pageBreak;l->value=p;r->value=q;l->source.dirty=r->source.dirty=true;auto after=*flow;after.blocks[at]=l;after.blocks.insert(at+1,r);Command c;c.name=pageBreak?"쪽 나누기":"문단 나누기";c.flows.append({flow->id,*flow,after});c.after.anchor=c.after.caret={r->id,0};return execute(std::move(c));}
bool Editor::applyCharacter(const std::function<void(CharStyle&)>&fn){auto list=document.paragraphs();auto a=selection.anchor,z=selection.caret;int ai=-1,zi=-1;for(int i=0;i<list.size();++i){if(list[i].block->id==a.paragraph)ai=i;if(list[i].block->id==z.paragraph)zi=i;}if(ai<0||zi<0)return false;if(ai>zi||(ai==zi&&a.offset>z.offset)){std::swap(ai,zi);std::swap(a,z);}Command c;c.name="글자 모양";c.after=selection;for(int i=ai;i<=zi;++i){auto b=list[i].block;if(!editable(b))return false;auto p=*b->paragraph();int l=i==ai?a.offset:0,h=i==zi?z.offset:p.length();if(selection.empty()){l=0;h=p.length();}auto before=sliceRuns(p,0,l),middle=sliceRuns(p,l,h),after=sliceRuns(p,h,p.length());if(middle.isEmpty())middle.append(Run{{},p.styleAt(l),{},{},{},{}});for(auto&r:middle){fn(r.style);r.style.sourceId.clear();}p.runs=normalizeRuns(before+middle+after);if(p.runs.isEmpty())p.runs=middle;auto n=std::make_shared<Block>(*b);n->value=p;n->source.dirty=true;c.blocks.append({b->id,b,n});}return execute(std::move(c));}
bool Editor::applyParagraph(const std::function<void(ParaStyle&)>&fn){auto list=document.paragraphs();int a=-1,z=-1;for(int i=0;i<list.size();++i){if(list[i].block->id==selection.anchor.paragraph)a=i;if(list[i].block->id==selection.caret.paragraph)z=i;}if(a<0||z<0)return false;if(a>z)std::swap(a,z);Command c;c.name="문단 모양";c.after=selection;for(int i=a;i<=z;++i){auto b=list[i].block;if(!editable(b))return false;auto n=std::make_shared<Block>(*b);auto p=*b->paragraph();fn(p.style);p.style.sourceId.clear();n->value=p;n->source.dirty=true;c.blocks.append({b->id,b,n});}return execute(std::move(c));}
bool Editor::insertObject(BlockPtr o){if(!o)return false;auto b=document.block(selection.caret.paragraph);if(!b||!b->paragraph())return false;return insertRuns({Run{{},b->paragraph()->styleAt(selection.caret.offset),o,{},{},{}}});}
bool Editor::updateBlock(BlockPtr n,const QString&label){if(!n)return false;auto b=document.block(n->id);if(!b||b->source.opaque)return false;auto copy=std::make_shared<Block>(*n);copy->source.dirty=true;Command c;c.name=label;c.blocks.append({b->id,b,copy});c.after=selection;return execute(std::move(c));}
bool Editor::updatePage(int s,const PageFormat&p){if(s<0||s>=document.sections.size())return false;Command c;c.name="편집 용지";c.pages.append({document.sections[s].id,document.sections[s].page,p});c.after=selection;return execute(std::move(c));}
}
