#include <hwpedit/formats.hpp>
#include <QFile>
#include <QFileInfo>
#include <QSaveFile>
#include <QTemporaryFile>
#include <QDir>
#include <QSet>
#include <QXmlStreamReader>
#include <zip.h>
#include <memory>
#include <limits>
#ifdef Q_OS_UNIX
#include <fcntl.h>
#include <unistd.h>
#endif
namespace he {
QString errorName(ErrorCode c){switch(c){case ErrorCode::Io:return "IoFailure";case ErrorCode::InvalidContainer:return "InvalidContainer";case ErrorCode::InvalidHeader:return "InvalidHeader";case ErrorCode::InvalidXml:return "InvalidXml";case ErrorCode::CorruptRecord:return "CorruptRecord";case ErrorCode::ResourceLimit:return "ResourceLimit";case ErrorCode::UnsupportedEncryption:return "UnsupportedEncryption";case ErrorCode::UnsupportedFeature:return "UnsupportedFeature";case ErrorCode::UnsafeSave:return "UnsafeSave";case ErrorCode::InvalidEdit:return "InvalidEdit";}return "UnknownError";}
Result<QByteArray> readFile(const QString&p,const Limits&l){QFile f(p);if(!f.open(QIODevice::ReadOnly))return std::unexpected(Error{ErrorCode::Io,p,f.errorString()});if(f.size()<0||quint64(f.size())>l.fileBytes)return std::unexpected(Error{ErrorCode::ResourceLimit,p,"File exceeds input budget"});auto b=f.readAll();if(f.error()!=QFileDevice::NoError)return std::unexpected(Error{ErrorCode::Io,p,f.errorString()});return b;}
Result<void> atomicWrite(const QString&p,const QByteArray&b){QSaveFile f(p);f.setDirectWriteFallback(false);if(!f.open(QIODevice::WriteOnly))return std::unexpected(Error{ErrorCode::Io,p,f.errorString()});if(f.write(b)!=b.size()||!f.flush()){f.cancelWriting();return std::unexpected(Error{ErrorCode::Io,p,f.errorString()});}
#ifdef Q_OS_UNIX
if(::fsync(f.handle())!=0){f.cancelWriting();return std::unexpected(Error{ErrorCode::Io,p,"fsync failed; original file was not replaced"});}
#endif
if(!f.commit())return std::unexpected(Error{ErrorCode::Io,p,f.errorString()});
#ifdef Q_OS_UNIX
int fd=::open(QFile::encodeName(QFileInfo(p).absolutePath()).constData(),O_DIRECTORY|O_RDONLY|O_CLOEXEC);if(fd>=0){int rc=::fsync(fd);::close(fd);if(rc!=0)return std::unexpected(Error{ErrorCode::Io,p,"File was saved but directory durability could not be confirmed"});}
#endif
return {};}
static bool safePath(const QString&n){if(n.isEmpty()||n.startsWith('/')||n.contains('\\')||n.contains(':')||n.contains(QChar(0)))return false;const auto parts=n.split('/');for(int i=0;i<parts.size();++i)if(parts[i]==".."||parts[i]=="."||(parts[i].isEmpty()&&i+1<parts.size()))return false;return true;}
Result<QMap<QString,QByteArray>> readZip(const QByteArray&b,const Limits&l){if(quint64(b.size())>l.fileBytes)return std::unexpected(Error{ErrorCode::ResourceLimit,{},"ZIP input budget exceeded"});zip_error_t err;zip_error_init(&err);auto src=zip_source_buffer_create(b.constData(),zip_uint64_t(b.size()),0,&err);if(!src){QString m=QString::fromUtf8(zip_error_strerror(&err));zip_error_fini(&err);return std::unexpected(Error{ErrorCode::InvalidContainer,{},m});}zip_t*raw=zip_open_from_source(src,ZIP_RDONLY,&err);if(!raw){zip_source_free(src);QString m=QString::fromUtf8(zip_error_strerror(&err));zip_error_fini(&err);return std::unexpected(Error{ErrorCode::InvalidContainer,{},m});}zip_error_fini(&err);std::unique_ptr<zip_t,decltype(&zip_discard)>z(raw,zip_discard);auto count=zip_get_num_entries(z.get(),0);if(count<0||count>l.zipEntries)return std::unexpected(Error{ErrorCode::ResourceLimit,{},"ZIP entry count limit exceeded"});QMap<QString,QByteArray>out;QSet<QString>names;quint64 total=0;
for(zip_uint64_t i=0;i<zip_uint64_t(count);++i){zip_stat_t st;zip_stat_init(&st);if(zip_stat_index(z.get(),i,0,&st)!=0||!(st.valid&ZIP_STAT_NAME)||!(st.valid&ZIP_STAT_SIZE))return std::unexpected(Error{ErrorCode::InvalidContainer,{},"Invalid ZIP directory"});QString name=QString::fromUtf8(st.name);if(!safePath(name)||names.contains(name))return std::unexpected(Error{ErrorCode::InvalidContainer,name,"Unsafe or duplicate package path"});names.insert(name);if(st.encryption_method!=ZIP_EM_NONE)return std::unexpected(Error{ErrorCode::UnsupportedEncryption,name,"Encrypted ZIP entries are not supported"});if(st.size>l.partBytes||st.size>l.expandedBytes-total||st.size>quint64(std::numeric_limits<int>::max()))return std::unexpected(Error{ErrorCode::ResourceLimit,name,"Expanded package budget exceeded"});total+=st.size;if(st.comp_size&&st.size/st.comp_size>2000)return std::unexpected(Error{ErrorCode::ResourceLimit,name,"Suspicious compression ratio"});if(name.endsWith('/'))continue;auto f=zip_fopen_index(z.get(),i,0);if(!f)return std::unexpected(Error{ErrorCode::InvalidContainer,name,QString::fromUtf8(zip_strerror(z.get()))});QByteArray data(int(st.size),Qt::Uninitialized);zip_uint64_t read=0;bool ok=true;while(read<st.size){auto n=zip_fread(f,data.data()+read,st.size-read);if(n<=0){ok=false;break;}read+=zip_uint64_t(n);}char extra=0;if(ok&&zip_fread(f,&extra,1)!=0)ok=false;if(zip_fclose(f)!=0)ok=false;if(!ok)return std::unexpected(Error{ErrorCode::InvalidContainer,name,"Truncated data or failed ZIP CRC"});out.insert(name,std::move(data));}return out;}
Result<QByteArray> writeZip(const QMap<QString,QByteArray>&parts){QTemporaryFile tmp;tmp.setAutoRemove(true);if(!tmp.open())return std::unexpected(Error{ErrorCode::Io,{},tmp.errorString()});QString path=tmp.fileName();tmp.close();int err=0;zip_t*z=zip_open(QFile::encodeName(path).constData(),ZIP_CREATE|ZIP_TRUNCATE,&err);if(!z)return std::unexpected(Error{ErrorCode::Io,path,"Cannot create package"});QStringList keys=parts.keys();if(keys.removeOne("mimetype"))keys.prepend("mimetype");for(const auto&k:keys){if(!safePath(k)){zip_discard(z);return std::unexpected(Error{ErrorCode::InvalidContainer,k,"Unsafe output path"});}const auto&b=parts.constFind(k).value();auto s=zip_source_buffer(z,b.constData(),zip_uint64_t(b.size()),0);if(!s){QString msg=QString::fromUtf8(zip_strerror(z));zip_discard(z);return std::unexpected(Error{ErrorCode::Io,k,msg});}auto n=zip_file_add(z,k.toUtf8().constData(),s,ZIP_FL_ENC_UTF_8);if(n<0){zip_source_free(s);QString msg=QString::fromUtf8(zip_strerror(z));zip_discard(z);return std::unexpected(Error{ErrorCode::Io,k,msg});}if(zip_set_file_compression(z,zip_uint64_t(n),k=="mimetype"?ZIP_CM_STORE:ZIP_CM_DEFLATE,6)!=0){zip_discard(z);return std::unexpected(Error{ErrorCode::Io,k,"Cannot configure compression"});}zip_file_set_mtime(z,zip_uint64_t(n),0,0);}if(zip_close(z)!=0){QString m=QString::fromUtf8(zip_strerror(z));zip_discard(z);return std::unexpected(Error{ErrorCode::Io,path,m});}QFile file(path);if(!file.open(QIODevice::ReadOnly))return std::unexpected(Error{ErrorCode::Io,path,file.errorString()});return file.readAll();}
Result<QDomDocument> readXml(const QByteArray&b,const QString&p,const Limits&l){if(quint64(b.size())>l.partBytes)return std::unexpected(Error{ErrorCode::ResourceLimit,p,"XML byte budget exceeded"});QXmlStreamReader scan(b);scan.setEntityExpansionLimit(32);int depth=0,nodes=0;while(!scan.atEnd()){auto t=scan.readNext();if(t==QXmlStreamReader::DTD||t==QXmlStreamReader::EntityReference)return std::unexpected(Error{ErrorCode::InvalidXml,p,"DTD and unresolved entities are prohibited"});if(t==QXmlStreamReader::StartElement){if(++depth>l.xmlDepth||++nodes>l.xmlNodes)return std::unexpected(Error{ErrorCode::ResourceLimit,p,"XML structural budget exceeded"});}else if(t==QXmlStreamReader::EndElement)--depth;}if(scan.hasError())return std::unexpected(Error{ErrorCode::InvalidXml,p,QString("%1 at %2:%3").arg(scan.errorString()).arg(scan.lineNumber()).arg(scan.columnNumber())});QDomDocument doc;QString message;int line=0,col=0;if(!doc.setContent(b,true,&message,&line,&col))return std::unexpected(Error{ErrorCode::InvalidXml,p,QString("%1 at %2:%3").arg(message).arg(line).arg(col)});return doc;}
namespace xml {
bool is(const QDomElement&e,const QString&ns,const QString&n){return !e.isNull()&&e.namespaceURI()==ns&&e.localName()==n;}
QVector<QDomElement>children(const QDomElement&e,const QString&ns,const QString&name){QVector<QDomElement>out;for(auto n=e.firstChild();!n.isNull();n=n.nextSibling()){auto c=n.toElement();if(!c.isNull()&&c.namespaceURI()==ns&&(name.isEmpty()||c.localName()==name))out.append(c);}return out;}
QDomElement child(const QDomElement&e,const QString&ns,const QString&name){auto c=children(e,ns,name);return c.isEmpty()?QDomElement{}:c.first();}
QDomElement descendant(const QDomElement&e,const QString&ns,const QString&name){if(is(e,ns,name))return e;for(auto n=e.firstChildElement();!n.isNull();n=n.nextSiblingElement()){auto out=descendant(n,ns,name);if(!out.isNull())return out;}return {};}
QDomElement add(QDomNode parent,const QString&ns,const QString&name){auto doc=parent.isDocument()?parent.toDocument():parent.ownerDocument();auto e=doc.createElementNS(ns,name);parent.appendChild(e);return e;}
QDomElement ensure(QDomNode parent,const QString&ns,const QString&q){auto n=child(parent.toElement(),ns,q.section(':',-1));return n.isNull()?add(parent,ns,q):n;}
void removeChildren(QDomNode p,const QString&ns,const QString&name){for(auto n=p.firstChild();!n.isNull();){auto next=n.nextSibling();auto e=n.toElement();if(!e.isNull()&&e.namespaceURI()==ns&&(name.isEmpty()||e.localName()==name))p.removeChild(n);n=next;}}
QByteArray fragment(const QDomElement&e){if(e.isNull())return {};QDomDocument d;auto root=d.importNode(e,true).toElement();d.appendChild(root);for(const auto&kv:QList<QPair<QString,QString>>{{"hp",hp},{"hh",hh},{"hc",hc},{"hs",hs},{"ha",ha},{"opf",opf}})root.setAttribute("xmlns:"+kv.first,kv.second);for(auto p=e.parentNode();!p.isNull();p=p.parentNode()){auto attrs=p.attributes();for(int i=0;i<attrs.size();++i){auto a=attrs.item(i).toAttr();if(a.name().startsWith("xmlns")&&!root.hasAttribute(a.name()))root.setAttribute(a.name(),a.value());}}return d.toByteArray(-1);}
QDomElement import(QDomDocument&dest,const QByteArray&b){auto d=readXml(b,"preserved XML");return d?dest.importNode(d->documentElement(),true).toElement():QDomElement{};}
qint64 integer(const QDomElement&e,const QString&key,qint64 fallback){bool ok=false;auto n=e.attribute(key).toLongLong(&ok);return ok?n:fallback;}
bool boolean(const QDomElement&e,const QString&key,bool fallback){if(!e.hasAttribute(key))return fallback;auto v=e.attribute(key);return v=="1"||v=="true";}
QString color(const QColor&c){return c.alpha()==0?"none":c.name(QColor::HexRgb).toUpper();}
QColor color(const QString&s,const QColor&fallback){if(s=="none"||s=="NONE")return QColor(Qt::transparent);QColor c(s);return c.isValid()?c:fallback;}
}
}
