// 본 제품은 한컴의 HWP 문서 파일(.hwp) 공개 문서를 참고하여 개발하였습니다.
#include <hwpedit/formats.hpp>
#include <hwpedit/unicode.hpp>
#include <QDir>
#include <QRegularExpression>
#include <algorithm>
#include <cmath>
namespace he { namespace {
using namespace xml;
struct BorderSet { Border edges[4]; QColor background=Qt::transparent; };
Alignment alignment(const QString&s){if(s=="CENTER")return Alignment::Center;if(s=="RIGHT")return Alignment::Right;if(s=="JUSTIFY")return Alignment::Justify;if(s=="DISTRIBUTE"||s=="DISTRIBUTE_SPACE")return Alignment::Distributed;return Alignment::Left;}
QDomElement effective(const QDomElement&e,const QString&ns,const QString&name){auto direct=child(e,ns,name);if(!direct.isNull())return direct;auto sw=child(e,hp,"switch");auto fallback=child(sw,hp,"default");return fallback.isNull()?QDomElement{}:descendant(fallback,ns,name);}
class Reader {
    Limits limits;
    Document doc;
    std::shared_ptr<Origin> origin=std::make_shared<Origin>();
    QMap<QString,CharStyle> chars;
    QMap<QString,ParaStyle> paras;
    QMap<QString,BorderSet> borders;
    QMap<QString,QString> styleNames;
    QMap<QString,QMap<QString,QString>> fonts;
    QString part;
    int pCount=0,cellCount=0;
    quint64 sourceBytes=0;
    [[noreturn]] void fail(ErrorCode code,const QString&m)const{throw Error{code,part,m};}
    Source source(const QDomElement&e){Source s;s.xml=fragment(e);sourceBytes+=quint64(s.xml.size());if(sourceBytes>limits.expandedBytes)fail(ErrorCode::ResourceLimit,"Preservation buffer limit exceeded");s.part=part;s.key=e.attribute("id");s.dirty=false;return s;}
    QDomDocument xmlPart(const QString&name){auto it=origin->parts.constFind(name);if(it==origin->parts.cend())throw Error{ErrorCode::InvalidHeader,name,"Required package part is missing"};auto d=readXml(it.value(),name,limits);if(!d)throw d.error();return *d;}
    QString resolve(const QString&href,const QString&base){if(href.contains(':')||href.contains('\\')||href.startsWith('/'))fail(ErrorCode::InvalidContainer,"External or absolute resource reference rejected");if(origin->parts.contains(href))return href;auto path=QDir::cleanPath(QFileInfo(base).path()+"/"+href);if(path==".."||path.startsWith("../"))fail(ErrorCode::InvalidContainer,"Resource reference escapes package root");return path;}
    void readHeader(const QString&name){part=name;auto hd=xmlPart(name);auto root=hd.documentElement();if(!is(root,hh,"head"))fail(ErrorCode::InvalidHeader,"Expected namespace-qualified hh:head");auto refs=child(root,hh,"refList");
        for(const auto&face:children(child(refs,hh,"fontfaces"),hh,"fontface")){auto&lang=fonts[face.attribute("lang")];for(const auto&f:children(face,hh,"font"))lang.insert(f.attribute("id"),f.attribute("face"));}
        for(const auto&e:children(child(refs,hh,"borderFills"),hh,"borderFill")){BorderSet bs;const QStringList names={"leftBorder","topBorder","rightBorder","bottomBorder"};for(int i=0;i<4;++i){auto x=child(e,hh,names[i]);auto type=x.attribute("type","NONE");bs.edges[i].style=type=="NONE"?0:type.contains("DOUBLE")?4:type.contains("DASH")?2:type.contains("DOT")?3:1;bs.edges[i].color=xml::color(x.attribute("color"));QString w=x.attribute("width","0.1 mm");double v=w.section(' ',0,0).toDouble();bs.edges[i].width=w.contains("mm")?v*72/25.4:v;}bs.background=xml::color(descendant(e,hc,"winBrush").attribute("faceColor","none"),Qt::transparent);borders.insert(e.attribute("id"),bs);}
        const QStringList langs={"hangul","latin","hanja","japanese","other","symbol","user"};
        for(const auto&e:children(child(refs,hh,"charProperties"),hh,"charPr")){CharStyle c;c.sourceId=e.attribute("id");c.size=double(integer(e,"height",1000))/100;c.color=xml::color(e.attribute("textColor","#000000"));c.background=xml::color(e.attribute("shadeColor","none"),Qt::transparent);auto f=child(e,hh,"fontRef");for(const auto&lang:langs)c.languageFonts.append(fonts.value(lang.toUpper()).value(f.attribute(lang),c.family));if(!c.languageFonts.isEmpty())c.family=c.languageFonts.first();c.bold=!child(e,hh,"bold").isNull();c.italic=!child(e,hh,"italic").isNull();auto u=child(e,hh,"underline");c.underline=u.attribute("type","NONE")!="NONE";c.underlineColor=xml::color(u.attribute("color"));c.strike=child(e,hh,"strikeout").attribute("shape","NONE")!="NONE";c.outline=child(e,hh,"outline").attribute("type","NONE")!="NONE";auto sh=child(e,hh,"shadow");c.shadow=sh.attribute("type","NONE")!="NONE";c.shadowColor=xml::color(sh.attribute("color","#808080"));c.width=integer(child(e,hh,"ratio"),"hangul",100);c.spacing=integer(child(e,hh,"spacing"),"hangul",0);c.relativeSize=integer(child(e,hh,"relSz"),"hangul",100);c.baseline=integer(child(e,hh,"offset"),"hangul",0);c.script=!child(e,hh,"supscript").isNull()?1:!child(e,hh,"subscript").isNull()?-1:0;chars.insert(c.sourceId,c);}
        QMap<QString,QVector<Unit>> tabs;for(auto e:children(child(refs,hh,"tabProperties"),hh,"tabPr")){QVector<Unit>v;for(auto t:children(e,hh,"tabItem"))v.append(integer(t,"pos"));tabs.insert(e.attribute("id"),v);}
        for(const auto&e:children(child(refs,hh,"paraProperties"),hh,"paraPr")){ParaStyle p;p.sourceId=e.attribute("id");p.alignment=alignment(child(e,hh,"align").attribute("horizontal"));auto m=effective(e,hh,"margin");p.left=integer(child(m,hc,"left"),"value");p.right=integer(child(m,hc,"right"),"value");p.indent=integer(child(m,hc,"intent"),"value");p.before=integer(child(m,hc,"prev"),"value");p.after=integer(child(m,hc,"next"),"value");auto sp=effective(e,hh,"lineSpacing");QString type=sp.attribute("type","PERCENT");p.spacingKind=type=="FIXED"?SpacingKind::Fixed:type=="AT_LEAST"?SpacingKind::Minimum:SpacingKind::Percent;p.lineSpacing=integer(sp,"value",160);if(p.spacingKind!=SpacingKind::Percent)p.lineSpacing/=100;auto br=child(e,hh,"breakSetting");p.keepNext=boolean(br,"keepWithNext");p.keepTogether=boolean(br,"keepLines");p.widowOrphan=boolean(br,"widowOrphan");p.breakBefore=boolean(br,"pageBreakBefore");p.tabs=tabs.value(e.attribute("tabPrIDRef"));auto h=child(e,hh,"heading");if(h.attribute("type")=="BULLET")p.listFormat=QStringLiteral("•");else if(h.attribute("type")=="NUMBER"||h.attribute("type")=="OUTLINE")p.listFormat="1.";p.listLevel=int(integer(h,"level"));paras.insert(p.sourceId,p);}
        for(const auto&e:children(child(refs,hh,"styles"),hh,"style")){Style s;s.name=e.attribute("name");s.character=chars.value(e.attribute("charPrIDRef"));s.paragraph=paras.value(e.attribute("paraPrIDRef"));doc.styles.insert(s.name,s);styleNames.insert(e.attribute("id"),s.name);}
        if(chars.isEmpty())fail(ErrorCode::InvalidHeader,"No character properties in header");if(paras.isEmpty())fail(ErrorCode::InvalidHeader,"No paragraph properties in header");
    }
    void page(const QDomElement&e,Section&s){auto p=child(e,hp,"pagePr");if(!p.isNull()){s.page.width=integer(p,"width",s.page.width);s.page.height=integer(p,"height",s.page.height);auto m=child(p,hp,"margin");s.page.left=integer(m,"left",s.page.left);s.page.right=integer(m,"right",s.page.right);s.page.top=integer(m,"top",s.page.top);s.page.bottom=integer(m,"bottom",s.page.bottom);s.page.binding=integer(m,"gutter");s.page.headerDistance=integer(m,"header",s.page.headerDistance);s.page.footerDistance=integer(m,"footer",s.page.footerDistance);}auto start=child(e,hp,"startNum");s.page.numberStart=std::max(1,int(integer(start,"page",1)));}
    QString text(const QDomElement&e,bool&opaque){QString out;for(auto n=e.firstChild();!n.isNull();n=n.nextSibling()){if(n.isText()||n.isCDATASection())out+=n.nodeValue();else if(auto c=n.toElement();!c.isNull()){if(is(c,hp,"tab"))out+='\t';else if(is(c,hp,"lineBreak"))out+=QChar(0x2028);else if(is(c,hp,"nbSpace"))out+=QChar(0xa0);else if(is(c,hp,"fwSpace"))out+=QChar(0x3000);else if(is(c,hp,"hyphen"))out+='-';else{opaque=true;out+=c.text();}}}return out;}
    BlockPtr unknown(const QDomElement&e){auto b=std::make_shared<Block>();b->value=Unknown{e.tagName(),"Preserved, not interpreted"};b->source=source(e);b->source.opaque=true;doc.warnings.append("미지원 개체 보존: "+e.tagName());return b;}
    Flow sublist(const QDomElement&e,int depth,Section&s){Flow out;for(auto p:children(e,hp,"p"))out.blocks.append(par(p,depth+1,s));if(out.blocks.isEmpty())out.blocks.append(paragraph());return out;}
    BlockPtr object(const QDomElement&e,int depth,Section&s){if(depth>limits.objectDepth)fail(ErrorCode::ResourceLimit,"Object nesting limit exceeded");auto b=std::make_shared<Block>();b->source=source(e);
        if(is(e,hp,"tbl")){Table t;t.rows=int(integer(e,"rowCnt"));t.columns=int(integer(e,"colCnt"));if(t.rows<1||t.columns<1||t.rows>10000||t.columns>1000||qint64(t.rows)*t.columns>limits.tableCells)fail(ErrorCode::ResourceLimit,"Invalid table grid");auto sz=child(e,hp,"sz");Unit width=integer(sz,"width",mm(150));t.widths=QVector<Unit>(t.columns,std::max<Unit>(100,width/t.columns));t.repeatHeading=boolean(e,"repeatHeader");t.allowRowSplit=e.attribute("pageBreak")=="CELL";auto pos=child(e,hp,"pos");t.alignment=alignment(pos.attribute("horzAlign"));for(auto row:children(e,hp,"tr"))for(auto ce:children(row,hp,"tc")){if(++cellCount>limits.tableCells)fail(ErrorCode::ResourceLimit,"Table cell budget exceeded");Cell c;c.source=source(ce);auto a=child(ce,hp,"cellAddr"),span=child(ce,hp,"cellSpan"),cs=child(ce,hp,"cellSz"),m=child(ce,hp,"cellMargin");c.row=int(integer(a,"rowAddr"));c.col=int(integer(a,"colAddr"));c.rowSpan=int(integer(span,"rowSpan",1));c.colSpan=int(integer(span,"colSpan",1));c.minimumHeight=integer(cs,"height",1800);c.left=integer(m,"left",283);c.right=integer(m,"right",283);c.top=integer(m,"top",141);c.bottom=integer(m,"bottom",141);auto sl=child(ce,hp,"subList");auto va=sl.attribute("vertAlign");c.verticalAlign=va=="CENTER"?1:va=="BOTTOM"?2:0;c.content=sublist(sl,depth,s);auto bs=borders.value(ce.attribute("borderFillIDRef"));c.background=bs.background;for(int i=0;i<4;++i)c.borders[i]=bs.edges[i];if(c.colSpan==1&&c.col>=0&&c.col<t.columns)t.widths[c.col]=std::max<Unit>(100,integer(cs,"width",t.widths[c.col]));t.cells.append(c);}t.caption=child(e,hp,"caption").text();b->value=t;return b;}
        if(is(e,hp,"equation")){b->value=Equation{child(e,hp,"script").text(),double(integer(e,"baseUnit",1200))/100};return b;}
        if(is(e,hp,"footNote")||is(e,hp,"endNote")){Note n;n.endnote=e.localName()=="endNote";n.content=sublist(child(e,hp,"subList"),depth,s);b->value=n;return b;}
        if(e.namespaceURI()==hp&&QStringList{"pic","rect","ellipse","line","polygon"}.contains(e.localName())){Graphic g;auto name=e.localName();g.kind=name=="pic"?GraphicKind::Image:name=="ellipse"?GraphicKind::Ellipse:name=="line"?GraphicKind::Line:name=="polygon"?GraphicKind::Polygon:GraphicKind::Rectangle;auto sz=child(e,hp,"sz");if(sz.isNull())sz=child(e,hp,"curSz");g.width=std::max<Unit>(1,integer(sz,"width",14400));g.height=std::max<Unit>(1,integer(sz,"height",7200));auto p=child(e,hp,"pos");g.x=integer(p,"horzOffset");g.y=integer(p,"vertOffset");g.anchor=boolean(p,"treatAsChar",true)?Anchor::Inline:p.attribute("vertRelTo")=="PAGE"?Anchor::Page:Anchor::Paragraph;auto wrap=e.attribute("textWrap","TOP_AND_BOTTOM");g.wrap=g.anchor==Anchor::Inline?Wrap::Inline:wrap=="SQUARE"?Wrap::Square:wrap=="TIGHT"?Wrap::Tight:wrap=="BEHIND_TEXT"?Wrap::Behind:wrap=="IN_FRONT_OF_TEXT"?Wrap::Front:Wrap::TopBottom;g.z=int(integer(e,"zOrder"));g.rotation=integer(child(e,hp,"rotationInfo"),"angle");auto im=descendant(e,hc,"img");g.resource=im.attribute("binaryItemIDRef");g.opacity=1.0-double(integer(im,"alpha",0))/255;g.alt=child(e,hp,"shapeComment").text();auto line=child(e,hp,"lineShape");g.stroke.color=xml::color(line.attribute("color"));g.stroke.width=points(integer(line,"width",50));auto lineStyle=line.attribute("style","SOLID");g.stroke.style=lineStyle=="NONE"?0:lineStyle.contains("DASH")?2:lineStyle.contains("DOT")?3:1;g.fill=xml::color(descendant(e,hc,"winBrush").attribute("faceColor","none"),Qt::transparent);auto box=child(e,hp,"drawText");if(!box.isNull()){g.kind=GraphicKind::TextBox;g.content=sublist(child(box,hp,"subList"),depth,s);}if(g.kind==GraphicKind::Image&&!doc.resources.contains(g.resource))doc.warnings.append("그림 리소스 누락: "+g.resource);b->value=g;return b;}
        return unknown(e);
    }
    void control(const QDomElement&e,Paragraph&p,Section&s,const CharStyle&cs,int depth,bool&opaque){
        if(is(e,hp,"secPr")){page(e,s);return;}
        if(is(e,hp,"colPr")){s.page.columns=int(integer(e,"colCount",1));s.page.columnGap=integer(e,"sameGap",s.page.columnGap);return;}
        if(is(e,hp,"pageNum")){const QStringList pos={"TOP_LEFT","TOP_CENTER","TOP_RIGHT","BOTTOM_LEFT","BOTTOM_CENTER","BOTTOM_RIGHT"};s.page.numberPosition=pos.indexOf(e.attribute("pos"))+1;return;}
        if(is(e,hp,"header")||is(e,hp,"footer")){if(e.attribute("applyPageType","BOTH")!="BOTH"){opaque=true;p.runs.append(Run{{},cs,unknown(e),{},{},{}});return;}auto f=sublist(child(e,hp,"subList"),depth,s);if(e.localName()=="header")s.header=std::move(f);else s.footer=std::move(f);return;}
        if(is(e,hp,"autoNum")&&e.attribute("numType")=="PAGE"){p.runs.append(Run{{},cs,{},"page",{},fragment(e)});return;}
        if(is(e,hp,"ctrl")){for(auto c=e.firstChildElement();!c.isNull();c=c.nextSiblingElement())control(c,p,s,cs,depth+1,opaque);return;}
        auto obj=object(e,depth+1,s);if(std::holds_alternative<Unknown>(obj->value))opaque=true;p.runs.append(Run{{},cs,obj,{},{},{}});
    }
    BlockPtr par(const QDomElement&e,int depth,Section&s){if(depth>limits.objectDepth||++pCount>limits.paragraphs)fail(ErrorCode::ResourceLimit,"Paragraph or nesting budget exceeded");auto b=std::make_shared<Block>();b->source=source(e);Paragraph p;p.style=paras.value(e.attribute("paraPrIDRef"));p.style.breakBefore=p.style.breakBefore||boolean(e,"pageBreak");p.namedStyle=styleNames.value(e.attribute("styleIDRef"));bool opaque=false;for(auto rn=e.firstChildElement();!rn.isNull();rn=rn.nextSiblingElement()){if(is(rn,hp,"linesegarray"))continue;if(!is(rn,hp,"run")){opaque=true;continue;}auto cs=chars.value(rn.attribute("charPrIDRef"));for(auto n=rn.firstChild();!n.isNull();n=n.nextSibling()){auto el=n.toElement();if(el.isNull())continue;if(is(el,hp,"t")){Run r;r.text=text(el,opaque);r.style=cs;r.sourceXml=fragment(rn);p.runs.append(r);}else control(el,p,s,cs,depth,opaque);}}if(p.runs.isEmpty())p.runs.append(Run{{},chars.value("0"),{},{},{},{}});b->value=p;b->source.opaque=opaque;return b;}
public:
    explicit Reader(const Limits&l):limits(l){}
    Document run(const QByteArray&bytes){auto package=readZip(bytes,limits);if(!package)throw package.error();origin->format=Origin::Format::Hwpx;origin->original=bytes;origin->parts=std::move(*package);if(origin->parts.value("mimetype").trimmed()!="application/hwp+zip")fail(ErrorCode::InvalidHeader,"Package mimetype is not application/hwp+zip");QString contentPart="Contents/content.hpf";if(origin->parts.contains("META-INF/container.xml")){auto container=xmlPart("META-INF/container.xml");auto nodes=container.elementsByTagNameNS("urn:oasis:names:tc:opendocument:xmlns:container","rootfile");for(int i=0;i<nodes.size();++i){auto e=nodes.at(i).toElement();auto candidate=e.attribute("full-path");if(candidate.endsWith(".hpf")&&origin->parts.contains(candidate)){contentPart=candidate;break;}}}
        QString headerPart="Contents/header.xml";QMap<QString,QString>items;QStringList sections;
        if(origin->parts.contains(contentPart)){auto cp=xmlPart(contentPart);auto root=cp.documentElement();if(root.namespaceURI()!=opf)fail(ErrorCode::InvalidHeader,"Invalid OPF manifest namespace");auto mf=child(root,opf,"manifest");for(auto item:children(mf,opf,"item")){auto id=item.attribute("id");if(items.contains(id))fail(ErrorCode::InvalidHeader,"Duplicate manifest ID");QString path=resolve(item.attribute("href"),contentPart);items.insert(id,path);if(id=="header"||path.endsWith("/header.xml"))headerPart=path;auto mime=item.attribute("media-type");if(mime.startsWith("image/"))doc.resources.insert(id,Resource{origin->parts.value(path),mime,path});}for(auto ref:children(child(root,opf,"spine"),opf,"itemref")){auto path=items.value(ref.attribute("idref"));if(path!=headerPart&&!path.isEmpty())sections.append(path);}auto meta=child(root,opf,"metadata");for(auto m=meta.firstChildElement();!m.isNull();m=m.nextSiblingElement())doc.metadata.insert(m.localName(),m.text());}
        if(sections.isEmpty()){QRegularExpression re("^Contents/section([0-9]+)\\.xml$");QMap<int,QString>ordered;for(auto i=origin->parts.cbegin();i!=origin->parts.cend();++i){auto m=re.match(i.key());if(m.hasMatch())ordered.insert(m.captured(1).toInt(),i.key());}sections=ordered.values();doc.warnings.append("문서 spine이 없어 구역 파일 번호 순서를 사용했습니다.");}if(sections.isEmpty())fail(ErrorCode::InvalidHeader,"No document sections");readHeader(headerPart);for(const auto&name:sections){part=name;auto sd=xmlPart(name);auto root=sd.documentElement();if(!is(root,hs,"sec"))fail(ErrorCode::InvalidHeader,"Expected namespace-qualified hs:sec");Section sec;sec.source=source(root);for(auto p:children(root,hp,"p"))sec.body.blocks.append(par(p,0,sec));if(sec.body.blocks.isEmpty())sec.body.blocks.append(paragraph());doc.sections.append(sec);origin->sectionParts.append(name);}doc.origin=origin;doc.revision=0;auto valid=doc.validate(limits);if(!valid)throw valid.error();return doc;
    }
};
}
Result<Document> readHwpx(const QByteArray&b,const Limits&l){try{return Reader(l).run(b);}catch(const Error&e){return std::unexpected(e);}catch(const std::bad_alloc&){return std::unexpected(Error{ErrorCode::ResourceLimit,{},"Allocation budget exhausted"});}catch(const std::exception&e){return std::unexpected(Error{ErrorCode::InvalidContainer,{},QString::fromUtf8(e.what())});}}
}
